CREATE TABLE yz_sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  real_name VARCHAR(100),
  phone VARCHAR(50),
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_user_username (username)
) COMMENT='系统用户';

CREATE TABLE yz_sys_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_code VARCHAR(64) NOT NULL,
  role_name VARCHAR(100) NOT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_role_code (role_code)
) COMMENT='系统角色';

CREATE TABLE yz_md_unit (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  sort_no INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='计量单位';

CREATE TABLE yz_md_material (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  material_no VARCHAR(64) NOT NULL,
  name VARCHAR(150) NOT NULL,
  spec VARCHAR(150),
  unit_id BIGINT,
  unit_name VARCHAR(50),
  material_type VARCHAR(30) NOT NULL DEFAULT 'GOODS',
  barcode VARCHAR(100),
  enabled TINYINT NOT NULL DEFAULT 1,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_md_material_no (material_no),
  KEY idx_md_material_name (name)
) COMMENT='商品物料';

CREATE TABLE yz_md_partner (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  partner_no VARCHAR(64) NOT NULL,
  partner_type VARCHAR(20) NOT NULL,
  name VARCHAR(150) NOT NULL,
  contact_name VARCHAR(100),
  phone VARCHAR(50),
  address VARCHAR(255),
  enabled TINYINT NOT NULL DEFAULT 1,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_md_partner_no (partner_no),
  KEY idx_md_partner_type (partner_type)
) COMMENT='客户供应商';

CREATE TABLE yz_inv_warehouse (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  warehouse_no VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_inv_warehouse_no (warehouse_no)
) COMMENT='仓库';

CREATE TABLE yz_mfg_bom (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  bom_no VARCHAR(64) NOT NULL,
  name VARCHAR(150) NOT NULL,
  product_id BIGINT NOT NULL,
  product_name VARCHAR(150) NOT NULL,
  output_qty DECIMAL(24,6) NOT NULL DEFAULT 1,
  enabled TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mfg_bom_no (bom_no),
  KEY idx_mfg_bom_product (product_id)
) COMMENT='BOM';

CREATE TABLE yz_mfg_bom_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  bom_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  material_name VARCHAR(150) NOT NULL,
  required_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  loss_rate DECIMAL(10,4) NOT NULL DEFAULT 0,
  sort_no INT NOT NULL DEFAULT 0,
  remark VARCHAR(500),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_mfg_bom_item_bom (bom_id)
) COMMENT='BOM明细';

CREATE TABLE yz_mfg_process (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  process_no VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  wage_type VARCHAR(20) NOT NULL DEFAULT 'PIECE',
  unit_price DECIMAL(24,6) NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1,
  sort_no INT NOT NULL DEFAULT 0,
  remark VARCHAR(500),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mfg_process_no (process_no)
) COMMENT='工序';

CREATE TABLE yz_mfg_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_no VARCHAR(64) NOT NULL,
  task_date DATE NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  sales_order_no VARCHAR(64),
  customer_id BIGINT,
  customer_name VARCHAR(150),
  customer_order_no VARCHAR(100),
  product_id BIGINT NOT NULL,
  product_name VARCHAR(150) NOT NULL,
  ordered_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  plan_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  finished_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  scrap_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  plan_start_date DATE,
  plan_finish_date DATE,
  actual_finish_date DATE,
  material_status VARCHAR(20) NOT NULL DEFAULT 'NOT_ISSUED',
  process_status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
  stock_in_status VARCHAR(20) NOT NULL DEFAULT 'NOT_STOCKED',
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  marker VARCHAR(50),
  remark VARCHAR(500),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mfg_task_no (task_no),
  KEY idx_mfg_task_status (status),
  KEY idx_mfg_task_product (product_id)
) COMMENT='生产任务';

CREATE TABLE yz_mfg_task_material (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  material_name VARCHAR(150) NOT NULL,
  required_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  issued_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  returned_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  waste_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  used_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  sort_no INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_mfg_task_material_task (task_id)
) COMMENT='生产任务物料';

CREATE TABLE yz_mfg_material_issue (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  issue_no VARCHAR(64) NOT NULL,
  task_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  issue_user_id BIGINT,
  issue_user_name VARCHAR(100),
  issue_time DATETIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  remark VARCHAR(500),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mfg_issue_no (issue_no),
  KEY idx_mfg_issue_task (task_id)
) COMMENT='生产领料';

CREATE TABLE yz_mfg_process_report (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  report_no VARCHAR(64) NOT NULL,
  task_id BIGINT NOT NULL,
  process_id BIGINT NOT NULL,
  process_name VARCHAR(100) NOT NULL,
  worker_ids VARCHAR(500),
  worker_names VARCHAR(500),
  good_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  scrap_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  start_time DATETIME,
  end_time DATETIME,
  unit_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  total_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  piecework_status VARCHAR(20) NOT NULL DEFAULT 'UNSETTLED',
  remark VARCHAR(500),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mfg_process_report_no (report_no),
  KEY idx_mfg_process_report_task (task_id)
) COMMENT='工序汇报';

CREATE TABLE yz_mfg_quality_inspection (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  inspection_no VARCHAR(64) NOT NULL,
  task_id BIGINT NOT NULL,
  inspector_id BIGINT,
  inspector_name VARCHAR(100),
  good_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  defect_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  scrap_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
  defect_item_id BIGINT,
  defect_item_name VARCHAR(100),
  inspection_time DATETIME NOT NULL,
  remark VARCHAR(500),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mfg_inspection_no (inspection_no),
  KEY idx_mfg_inspection_task (task_id)
) COMMENT='生产质检';

CREATE TABLE yz_hr_employee (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  employee_no VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(50),
  department_name VARCHAR(100),
  position_name VARCHAR(100),
  user_id BIGINT,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  base_salary DECIMAL(24,6) NOT NULL DEFAULT 0,
  wage_type VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_hr_employee_no (employee_no)
) COMMENT='员工档案';

CREATE TABLE yz_payroll_salary_sheet (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  sheet_no VARCHAR(64) NOT NULL,
  salary_month VARCHAR(7) NOT NULL,
  employee_id BIGINT NOT NULL,
  employee_name VARCHAR(100) NOT NULL,
  base_salary DECIMAL(24,6) NOT NULL DEFAULT 0,
  attendance_salary DECIMAL(24,6) NOT NULL DEFAULT 0,
  piecework_salary DECIMAL(24,6) NOT NULL DEFAULT 0,
  overtime_salary DECIMAL(24,6) NOT NULL DEFAULT 0,
  deduction_amount DECIMAL(24,6) NOT NULL DEFAULT 0,
  payable_amount DECIMAL(24,6) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(24,6) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_salary_sheet_no (sheet_no),
  UNIQUE KEY uk_salary_month_employee (salary_month, employee_id)
) COMMENT='工资单';
